### ISSUE TITLE
Release DAG Factory 0.20

### ISSUE THREAD

**Issue by phanikumv** [astronomer/dag-factory#192] opened 2024-07-18 10:24 UTC
* https://github.com/astronomer/dag-factory/issues/206
* https://github.com/astronomer/dag-factory/issues/203
* https://github.com/astronomer/dag-factory/issues/205
* https://github.com/astronomer/dag-factory/issues/212

**Comment by tatiana** [comment] 2024-10-04 09:25
Closing since it's a duplicate of #217

**Closed** 2024-10-04 09:25 UTC
Labels: duplicate
